---
title: "Mean Quality Scores"
author: "David Ho"
date: "9/8/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Import

```{r}
R1 = read.delim("/Users/davidho/Desktop/talapas_output/1294_S1_L008_R1_001.fastq.gz_q_score_metrics.txt")
R2 = read.delim("/Users/davidho/Desktop/talapas_output/1294_S1_L008_R2_001.fastq.gz_q_score_metrics.txt")
R3 = read.delim("/Users/davidho/Desktop/talapas_output/1294_S1_L008_R3_001.fastq.gz_q_score_metrics.txt")
R4 = read.delim("/Users/davidho/Desktop/talapas_output/1294_S1_L008_R4_001.fastq.gz_q_score_metrics.txt")
```

### Graphs

```{r}
plot(R3[,1], 
     type="n", 
     ylim=c(30,40),
     ylab="Mean quality score",
     xlab="Bp position",
     main="Mean quality score for barcode reads")
lines(R2, col="red")
lines(R3)
legend(7, 32, legend=c("R2", "R3"), col=c("red", "black"), lty=1)
```


```{r}
plot(R1[,1],
     type="n", 
     ylim=c(30,40),
     ylab="Mean quality score",
     xlab="Bp position",
     main="Mean quality score for insert reads")
lines(R1, col="blue")
lines(R4, col="darkgreen")
legend(87, 32, legend=c("R1", "R4"), col=c("blue", "darkgreen"), lty=1)
```